### PR TITLE
[10.0] [ADD] analytic_plan_analysis

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Analytic Plan-Actual Analysis
=============================

Analyze the plan vs. actuals of your project
--------------------------------------------
Module for a better project costs analysis.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
It does not work. Besides, got the following when installing:

image

**Comment by nikul-serpentcs** [comment]
plan_analysis

@aheficent I think, please take the latest pull, In my Local is fine.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
