### PR TITLE
[10.0] [ADD] stock_analytic_account

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Stock Analytic Account
======================

Project Procurement
-------------------
Features of this module:

* Adds the analytic account to the stock move and quants
* Makes it possible to search stock moves by analytic account or its
  project manager
* Makes it possible to search picking lists by analytic account or its
  project manager

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by nikul-serpentcs** [comment]
@aheficent Commits are already preserved and can you please check the [history](https://github.com/nikul-serpentcs/pmis/commits/10.0-stock_analytic_account/stock_analytic_account).

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
The analytic account is duplicated in the stock move

image

Moreover, the button in the project form is missing

**Comment by nikul-serpentcs** [comment]
@aheficent removed analytic account is duplicated in the stock move.
 Could you please review again.

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
