### PR TITLE
[10.0] [ADD] Added a unit test case

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Analytic WIP Report
================
* Added a Unit Test Case

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
49 files? something is not ok

**Comment by AaronHForgeFlow** [comment]
@nikul-serpentcs can you recheck? this is adding too many changes

**Comment by nikul-serpentcs** [comment]
@aheficent Fixed files changed, Could you please check it.

**Comment by AaronHForgeFlow** [comment]
Can you rebase again @nikul-serpentcs ?

**Comment by nikul-serpentcs** [comment]
@aheficent rebased a branch,  Could you please check it.

**Comment by AaronHForgeFlow** [comment]
hmmm, maybe you will have to reset to 10.0 and then commit your changes again

**Comment by nikul-serpentcs** [comment]
@aheficent Travis is Finally Happy :smile:

**Comment by AaronHForgeFlow** [comment]
Thank you Nik! can you squash a bit the commmits?

**Comment by AaronHForgeFlow** [comment]
Thanks. Merging

**Pull request merged**
