### PR TITLE
[10.0] [ADD] Added a Unit Test Case

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Stock Analytic Account
======================
 * Added a Unit Test Case

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
Can you rebase this branch?

**Comment by nikul-serpentcs** [comment]
@aheficent Rebased Branch.

**Comment by AaronHForgeFlow** [comment]
Something it's not ok. 62 files changed

**Comment by AaronHForgeFlow** [comment]
@nikul-serpentcs can you recheck? This is modifying too many files

**Comment by nikul-serpentcs** [comment]
@aheficent Fixed files changed, Could you please check it.

**Pull request merged**
