### PR TITLE
[10.0] [ADD] account_analytic_cost_category

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Analytic Account Cost Category
==============================

Adds the cost category to analytic accounts.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
It's not indispensable to keep the history here but it'll be nice

**Comment by nikul-serpentcs** [comment]
@aheficent Commits are already preserved and can you please check the [history.](https://github.com/nikul-serpentcs/pmis/commits/10.0-account_analytic_cost_category/account_analytic_cost_category)

**Comment by AaronHForgeFlow** [comment]
@nikul-serpentcs yes you're right thanks

**Pull request merged**
